//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_Etablissement
    {
        public string Matricule { get; set; }
        public string IDEtablissement { get; set; }
        public bool Gestionnaire { get; set; }
        public bool Defaut { get; set; }
        public string IDMatrice { get; set; }
    }
}
