//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public string Num_Contrat { get; set; }
        public string Avenant { get; set; }
        public Nullable<System.DateTime> Date_début { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Temps_Base { get; set; }
        public string IDRégime { get; set; }
        public string Régime_Mod { get; set; }
        public Nullable<decimal> Base_contractuelle { get; set; }
        public bool RTT { get; set; }
        public bool travail_de_nuit { get; set; }
        public bool Règle_équivalence { get; set; }
        public bool MultiEtablissement { get; set; }
        public string Matricule_agent_remplace { get; set; }
        public string Motif_remplacement { get; set; }
        public string Convention_collective { get; set; }
        public string Num_contrat_base { get; set; }
        public string IDetablissement { get; set; }
        public string Matricule { get; set; }
        public decimal Report_CPA { get; set; }
        public int Report_Ancienneté { get; set; }
        public int Report_CESS { get; set; }
    }
}
