//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande_Absence
    {
        public string Matricule { get; set; }
        public System.DateTime Date_debut { get; set; }
        public System.DateTime Date_fin { get; set; }
        public string Type_Jour { get; set; }
        public string Commentaire_agent { get; set; }
        public string Commentaire_gestionnaire { get; set; }
        public string Etat { get; set; }
    }
}
