//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorairesType
    {
        public string Code_Horaire_Type { get; set; }
        public string IDetablissement { get; set; }
        public string Type_jour { get; set; }
        public Nullable<System.DateTime> deb_prise_1 { get; set; }
        public Nullable<System.DateTime> fin_prise_1 { get; set; }
        public string pause_1 { get; set; }
        public string Repas1 { get; set; }
        public string Type_prise_1 { get; set; }
        public Nullable<System.DateTime> deb_prise_2 { get; set; }
        public Nullable<System.DateTime> fin_prise_2 { get; set; }
        public string pause_2 { get; set; }
        public string Repas2 { get; set; }
        public string type_prise_2 { get; set; }
        public Nullable<System.DateTime> deb_prise_3 { get; set; }
        public Nullable<System.DateTime> fin_prise_3 { get; set; }
        public string type_prise_3 { get; set; }
        public string Repas3 { get; set; }
        public Nullable<System.DateTime> Durée { get; set; }
        public string type_durée { get; set; }
        public bool nuit { get; set; }
        public Nullable<int> Couleur { get; set; }
        public string Description { get; set; }
        public string IDService { get; set; }
        public string IDSection { get; set; }
    }
}
