//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamTransfertPaie
    {
        public string Matricule { get; set; }
        public string Modele { get; set; }
        public string Table { get; set; }
        public string Clef { get; set; }
        public string Libellé { get; set; }
        public string Description { get; set; }
        public short Unité { get; set; }
        public bool AffDate { get; set; }
        public bool AffNombre { get; set; }
        public int Ordre { get; set; }
        public string CodeRubrique { get; set; }
        public Nullable<short> Catégorie { get; set; }
        public System.DateTime Mois { get; set; }
        public System.DateTime Debut { get; set; }
        public System.DateTime Fin { get; set; }
    }
}
