//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning
    {
        public System.DateTime Jour { get; set; }
        public string Matricule { get; set; }
        public Nullable<int> Num_semaine { get; set; }
        public Nullable<int> Num_jour_année { get; set; }
        public Nullable<int> Num_jour_Semaine { get; set; }
        public Nullable<int> Num_mois { get; set; }
        public Nullable<int> Num_Jour_matrice { get; set; }
        public Nullable<int> Cycle { get; set; }
        public string Type_Jour { get; set; }
        public Nullable<System.DateTime> Heure_début1 { get; set; }
        public Nullable<System.DateTime> Heure_fin1 { get; set; }
        public string Pause1 { get; set; }
        public string Repas1 { get; set; }
        public string Type_Prise1 { get; set; }
        public string IDEtablissement1 { get; set; }
        public string IDSection1 { get; set; }
        public string IDService1 { get; set; }
        public Nullable<int> Couleur1 { get; set; }
        public bool Visible1 { get; set; }
        public bool Verrouiller1 { get; set; }
        public Nullable<System.DateTime> Heure_début2 { get; set; }
        public Nullable<System.DateTime> Heure_fin2 { get; set; }
        public string Pause2 { get; set; }
        public string Repas2 { get; set; }
        public string Type_Prise2 { get; set; }
        public string IDEtablissement2 { get; set; }
        public string IDSection2 { get; set; }
        public string IDService2 { get; set; }
        public Nullable<int> Couleur2 { get; set; }
        public bool Visible2 { get; set; }
        public bool Verrouiller2 { get; set; }
        public Nullable<System.DateTime> Heure_début3 { get; set; }
        public Nullable<System.DateTime> Heure_fin3 { get; set; }
        public string Repas3 { get; set; }
        public string Type_Prise3 { get; set; }
        public string IDEtablissement3 { get; set; }
        public string IDSection3 { get; set; }
        public string IDService3 { get; set; }
        public Nullable<int> Couleur3 { get; set; }
        public bool Visible3 { get; set; }
        public bool Verrouiller3 { get; set; }
        public Nullable<System.DateTime> Durée { get; set; }
        public string Type_Durée { get; set; }
        public string IDEtablissement_Durée { get; set; }
        public string IDSection_Durée { get; set; }
        public string IDService_Durée { get; set; }
        public Nullable<int> Couleur_Durée { get; set; }
        public bool Visible_Durée { get; set; }
        public bool Verrouiller_Durée { get; set; }
        public bool Férié { get; set; }
        public bool nuit { get; set; }
        public Nullable<int> BackColor { get; set; }
        public string Commentaire { get; set; }
        public Nullable<System.DateTime> Date_MAJ { get; set; }
        public string IDMatrice { get; set; }
    }
}
