//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Parametres
    {
        public string Nom { get; set; }
        public string Valeur { get; set; }
        public string Commentaire { get; set; }
        public Nullable<bool> Base { get; set; }
        public Nullable<System.DateTime> DateEntréeVigueur { get; set; }
        public string IDEtablissement { get; set; }
        public string Matricule { get; set; }
    }
}
