//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public string Matricule { get; set; }
        public string Civilité { get; set; }
        public bool Sexe { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Nom_jeune_fille { get; set; }
        public string Tél { get; set; }
        public string Portable { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public Nullable<decimal> Departement { get; set; }
        public string Ville { get; set; }
        public string Adresse { get; set; }
        public string Adresse_mail { get; set; }
        public bool Cadre { get; set; }
        public string N_SS { get; set; }
        public string Matricule_paie { get; set; }
        public Nullable<int> Coeff_base { get; set; }
        public Nullable<int> Coeff_MAJ { get; set; }
        public Nullable<decimal> CA_N { get; set; }
        public Nullable<decimal> CA_N_1 { get; set; }
        public Nullable<decimal> CS { get; set; }
        public bool RTT { get; set; }
        public string IDQualification { get; set; }
        public string IDEmploi { get; set; }
        public string IDFiliere { get; set; }
        public string IDPaie { get; set; }
        public string email { get; set; }
        public string Ordinateur { get; set; }
        public string FichierPhoto { get; set; }
        public string PasswordSalt { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordResetDate { get; set; }
        public string PasswordWeb { get; set; }
        public bool Supprimer { get; set; }
        public Nullable<System.DateTime> Date_derniere_modification { get; set; }
        public Nullable<System.DateTime> Date_création { get; set; }
        public string Session { get; set; }
        public string Commentaire { get; set; }
        public string MailserverType { get; set; }
        public string MailserverAddress { get; set; }
        public Nullable<short> MailServerPort { get; set; }
        public string MailUsername { get; set; }
        public string MailPassword { get; set; }
        public bool MailServerTLS { get; set; }
    }
}
