//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeRegime
    {
        public string IDCodeRegime { get; set; }
        public string LIBELLE_CodeRegime { get; set; }
        public Nullable<int> COULEUR_CodeRegime { get; set; }
        public Nullable<bool> SUPPRIMER_CodeRegime { get; set; }
    }
}
