//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploiDuTemp
    {
        public string IDEmploiDuTemps { get; set; }
        public string Code_Usager { get; set; }
        public string CodeActe { get; set; }
        public int NUMJOUR_EmploiDuTemps { get; set; }
        public System.DateTime HEUREDEBUT_EmploiDuTemps { get; set; }
        public System.DateTime HEUREFIN_EmploiDuTemps { get; set; }
        public Nullable<bool> HORSSITE_EmploiDuTemps { get; set; }
        public string DESCRIPTION_EmploiDuTemps { get; set; }
        public string TACHE_EmploiDuTemps { get; set; }
        public Nullable<int> NUMACTIVITE_EmploiDuTemps { get; set; }
        public Nullable<int> COULEUR_EmploiDuTemps { get; set; }
        public Nullable<System.DateTime> DATEDERNIEREMAJ_EmploiDuTemps { get; set; }
        public Nullable<int> NUMSEMAINE_EmploiDuTemps { get; set; }
        public Nullable<bool> SUPPRIMER_EmploiDuTemps { get; set; }
    }
}
