//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtabSuivi
    {
        public string IDEtabSuivi { get; set; }
        public string NOM_EtabSuivi { get; set; }
        public string CP_EtabSuivi { get; set; }
        public string VILLE_EtabSuivi { get; set; }
        public string ADRESSE_EtabSuivi { get; set; }
        public string TEL_EtabSuivi { get; set; }
        public Nullable<bool> SUPPRIMER_EtabSuivi { get; set; }
        public Nullable<int> COULEUR_EtabSuivi { get; set; }
    }
}
