//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamAppli
    {
        public string Version { get; set; }
        public string Format_Password { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string smtp { get; set; }
        public bool SSL { get; set; }
        public string email_smtp { get; set; }
        public string password_smtp { get; set; }
        public Nullable<int> port_SSL { get; set; }
        public string serveur_Name { get; set; }
        public bool Consultation_Agent { get; set; }
        public System.DateTime Date_Installation { get; set; }
        public Nullable<decimal> IntRenouvellement { get; set; }
        public string Site_Web_proget { get; set; }
        public string hot_line { get; set; }
        public string mail_maintenance { get; set; }
        public bool BoolCalculHoraire { get; set; }
        public bool BoolActivites { get; set; }
        public bool BoolCouleur { get; set; }
        public bool BoolRepas { get; set; }
        public Nullable<int> Durée_activité { get; set; }
        public string Logiciel_Paie { get; set; }
        public bool BoolTrace { get; set; }
        public bool BoolEquivalence { get; set; }
        public bool BoolError { get; set; }
        public bool BoolBornesRepas { get; set; }
        public Nullable<int> NbJoursArrière { get; set; }
    }
}
