//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamOfficiel
    {
        public string Nom { get; set; }
        public string Type { get; set; }
        public string Valeur { get; set; }
        public string Commentaire { get; set; }
        public bool Base { get; set; }
        public System.DateTime DateEntréeVigueur { get; set; }
        public bool Obligatoire { get; set; }
        public bool Supprimer { get; set; }
    }
}
