//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamUtilisateur
    {
        public string Matricule { get; set; }
        public bool Format_Horaire { get; set; }
        public bool MatriceVerticale { get; set; }
        public string ModelePaie { get; set; }
        public bool AffichageTreeView { get; set; }
        public bool ActiverBoutonSP { get; set; }
        public string CodificationTypeJour { get; set; }
    }
}
