//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relever
    {
        public string IDAllocation { get; set; }
        public string Code_Usager { get; set; }
        public Nullable<System.DateTime> DATEDECISION_Allocation { get; set; }
        public Nullable<System.DateTime> DATEDEBUT_Allocation { get; set; }
        public Nullable<System.DateTime> DATEFIN_Allocation { get; set; }
    }
}
