//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPCumul
    {
        public string Matricule { get; set; }
        public Nullable<decimal> TpsBase { get; set; }
        public Nullable<decimal> SeuilHSupp { get; set; }
        public Nullable<decimal> TpsW { get; set; }
        public Nullable<decimal> TpsAbs { get; set; }
        public Nullable<decimal> TpsAbsNP { get; set; }
        public Nullable<decimal> CPA { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> CA { get; set; }
        public Nullable<decimal> RTT { get; set; }
    }
}
