//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePriseEnCharge
    {
        public string IDTypePriseEnCharge { get; set; }
        public string LIBELLE_TypePriseEnCharge { get; set; }
        public Nullable<int> COULEUR_TypePriseEnCharge { get; set; }
        public Nullable<bool> SUPPRIMER_TypePriseEnCharge { get; set; }
    }
}
