//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usager
    {
        public string Code_Usager { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int Couleur { get; set; }
        public bool Supprimer { get; set; }
        public string IDDossierMedical { get; set; }
        public string IDCodeGestion { get; set; }
        public string IDCaisseSecu { get; set; }
        public string IDCodeRegime { get; set; }
        public string Adresse { get; set; }
        public string Code_Postal { get; set; }
        public System.DateTime Date_entree { get; set; }
        public System.DateTime Date_naissance { get; set; }
        public string email { get; set; }
        public string Portable { get; set; }
        public string NOMNAISSANCEUsager { get; set; }
        public string Sexe { get; set; }
        public string Tél { get; set; }
        public string Ville { get; set; }
        public string NUMSECUUsager { get; set; }
        public Nullable<System.DateTime> DATESORTIEUsager { get; set; }
        public string LieuNAISSUsager { get; set; }
        public string IDEtablissement { get; set; }
    }
}
