//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Edition_Archive_Apercu
    {
        public System.DateTime Date_Arch { get; set; }
        public System.DateTime Jour { get; set; }
        public Nullable<System.DateTime> Heure_début1 { get; set; }
        public Nullable<System.DateTime> Heure_fin1 { get; set; }
        public string Type_Prise1 { get; set; }
        public string IDEtablissement1 { get; set; }
        public string IDSection1 { get; set; }
        public string IDService1 { get; set; }
        public Nullable<System.DateTime> Heure_début2 { get; set; }
        public Nullable<System.DateTime> Heure_fin2 { get; set; }
        public string Type_Prise2 { get; set; }
        public string IDEtablissement2 { get; set; }
        public string IDSection2 { get; set; }
        public string IDService2 { get; set; }
        public Nullable<System.DateTime> Heure_début3 { get; set; }
        public Nullable<System.DateTime> Heure_fin3 { get; set; }
        public string IDEtablissement3 { get; set; }
        public string IDSection3 { get; set; }
        public string Type_Prise3 { get; set; }
        public string IDService3 { get; set; }
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
    }
}
