//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalTransaction
    {
        public System.DateTime DateEvt { get; set; }
        public string Matricule { get; set; }
        public int NumLigne { get; set; }
        public string Ecran { get; set; }
        public string description { get; set; }
        public bool Audit { get; set; }
    }
}
