//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamTransfertPaieColonne
    {
        public string Matricule { get; set; }
        public string Modele { get; set; }
        public string Libellé { get; set; }
        public string Description { get; set; }
        public short Ordre { get; set; }
        public bool Sélection { get; set; }
    }
}
