//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlandeServicesCouverture
    {
        public string PlanService { get; set; }
        public int Num_Semaine { get; set; }
        public Nullable<int> Roulement_Lundi { get; set; }
        public Nullable<int> Roulement_Mardi { get; set; }
        public Nullable<int> Roulement_Mercredi { get; set; }
        public Nullable<int> Roulement_Jeudi { get; set; }
        public Nullable<int> Roulement_Vendredi { get; set; }
        public Nullable<int> Roulement_Samedi { get; set; }
        public Nullable<int> Roulement_Dimanche { get; set; }
    }
}
