//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodificationActe
    {
        public string CodeActe { get; set; }
        public string Catégorie { get; set; }
        public string Code_Famille { get; set; }
        public string Libellé { get; set; }
        public int Couleur { get; set; }
        public bool Supprimer { get; set; }
        public Nullable<double> TARIFHT { get; set; }
    }
}
