//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinataire
    {
        public int CodeDestinataire { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string email { get; set; }
        public string Portable { get; set; }
        public string Société { get; set; }
        public string fonction { get; set; }
        public bool @public { get; set; }
        public string matricule { get; set; }
    }
}
