//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierMedical
    {
        public string IDDossierMedical { get; set; }
        public Nullable<System.DateTime> DATE_Consultation { get; set; }
        public string LIBELLE_Consultation { get; set; }
        public Nullable<int> COULEUR_Consultation { get; set; }
        public Nullable<bool> SUPPRIMER_Consultation { get; set; }
    }
}
