//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgetEntities : DbContext
    {
        public ProgetEntities()
            : base("name=ProgetEntities")
        {
        }
    
    	public ProgetEntities(string ConnectionString)
          : base(ConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent_Etablissement> Agent_Etablissement { get; set; }
        public virtual DbSet<Agent_PeriodeModulation> Agent_PeriodeModulation { get; set; }
        public virtual DbSet<Agent_Section> Agent_Section { get; set; }
        public virtual DbSet<Agent_Service> Agent_Service { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Allocation> Allocations { get; set; }
        public virtual DbSet<CaisseSecu> CaisseSecus { get; set; }
        public virtual DbSet<Calendrier> Calendriers { get; set; }
        public virtual DbSet<CalendrierCongés> CalendrierCongés { get; set; }
        public virtual DbSet<Catégories> Catégories { get; set; }
        public virtual DbSet<CETSouhait> CETSouhaits { get; set; }
        public virtual DbSet<CodeGestion> CodeGestions { get; set; }
        public virtual DbSet<CodeRegime> CodeRegimes { get; set; }
        public virtual DbSet<CodificationActe> CodificationActes { get; set; }
        public virtual DbSet<CodificationTypesJour> CodificationTypesJours { get; set; }
        public virtual DbSet<CongésScolaire> CongésScolaire { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contacts_Usagers> Contacts_Usagers { get; set; }
        public virtual DbSet<Contrat> Contrats { get; set; }
        public virtual DbSet<ConventionsCollective> ConventionsCollectives { get; set; }
        public virtual DbSet<Demande_Absence> Demande_Absence { get; set; }
        public virtual DbSet<Destinataire> Destinataires { get; set; }
        public virtual DbSet<DossierMedical> DossierMedicals { get; set; }
        public virtual DbSet<Droit> Droits { get; set; }
        public virtual DbSet<EmploiDuTemp> EmploiDuTemps { get; set; }
        public virtual DbSet<Emplois> Emplois { get; set; }
        public virtual DbSet<Etablissement_PeriodeModulation> Etablissement_PeriodeModulation { get; set; }
        public virtual DbSet<Etablissement_Service> Etablissement_Service { get; set; }
        public virtual DbSet<Etablissement> Etablissements { get; set; }
        public virtual DbSet<EtabSuivi> EtabSuivis { get; set; }
        public virtual DbSet<Famille> Familles { get; set; }
        public virtual DbSet<Filiere> Filieres { get; set; }
        public virtual DbSet<Fonction_Ecran> Fonction_Ecran { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<GestionDocument> GestionDocuments { get; set; }
        public virtual DbSet<HistoRCF> HistoRCFs { get; set; }
        public virtual DbSet<HistoRCFArchive> HistoRCFArchives { get; set; }
        public virtual DbSet<HorairesType> HorairesTypes { get; set; }
        public virtual DbSet<JFExclusRCF> JFExclusRCFs { get; set; }
        public virtual DbSet<JournalTransaction> JournalTransactions { get; set; }
        public virtual DbSet<Lieu> Lieux { get; set; }
        public virtual DbSet<MatriceActivite> MatriceActivites { get; set; }
        public virtual DbSet<Matrix> Matrices { get; set; }
        public virtual DbSet<MotifModif> MotifModifs { get; set; }
        public virtual DbSet<MotifsAvenant> MotifsAvenants { get; set; }
        public virtual DbSet<MotifsRemplacement> MotifsRemplacements { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<ParamAgent> ParamAgents { get; set; }
        public virtual DbSet<ParamAppli> ParamApplis { get; set; }
        public virtual DbSet<ParamEtablissement> ParamEtablissements { get; set; }
        public virtual DbSet<ParamOfficiel> ParamOfficiels { get; set; }
        public virtual DbSet<ParamTransfertPaie> ParamTransfertPaies { get; set; }
        public virtual DbSet<ParamTransfertPaieColonne> ParamTransfertPaieColonnes { get; set; }
        public virtual DbSet<ParamTransfertPaieModele> ParamTransfertPaieModeles { get; set; }
        public virtual DbSet<ParamUtilisateur> ParamUtilisateurs { get; set; }
        public virtual DbSet<PériodesActivités> PériodesActivités { get; set; }
        public virtual DbSet<PlandeService> PlandeServices { get; set; }
        public virtual DbSet<PlandeServicesBesoin> PlandeServicesBesoins { get; set; }
        public virtual DbSet<PlandeServicesCouverture> PlandeServicesCouvertures { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<PlanningArchive> PlanningArchives { get; set; }
        public virtual DbSet<PlanningPublie> PlanningPublies { get; set; }
        public virtual DbSet<PlanningUsager> PlanningUsagers { get; set; }
        public virtual DbSet<PriseEnCharge> PriseEnCharges { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<RCN1> RCN1 { get; set; }
        public virtual DbSet<RCPaye> RCPayes { get; set; }
        public virtual DbSet<Régimes> Régimes { get; set; }
        public virtual DbSet<Relever> Relevers { get; set; }
        public virtual DbSet<Responsabilite> Responsabilites { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SectionsUnités> SectionsUnités { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Statut> Statuts { get; set; }
        public virtual DbSet<Suivre> Suivres { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TMPCumul> TMPCumuls { get; set; }
        public virtual DbSet<Type5> Type5 { get; set; }
        public virtual DbSet<TypePriseEnCharge> TypePriseEnCharges { get; set; }
        public virtual DbSet<Usager> Usagers { get; set; }
        public virtual DbSet<V_Edition_Archive_Apercu> V_Edition_Archive_Apercu { get; set; }
        public virtual DbSet<V_Edition_Planning_Individuel> V_Edition_Planning_Individuel { get; set; }
        public virtual DbSet<V_Parametres> V_Parametres { get; set; }
    }
}
