//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Régimes
    {
        public string IDRégime { get; set; }
        public string Nom { get; set; }
        public bool RTT { get; set; }
        public bool Tps_Partiel { get; set; }
        public bool Tps_Plein { get; set; }
        public int Periode { get; set; }
        public bool CDD { get; set; }
        public bool Supprimer { get; set; }
    }
}
