//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCPaye
    {
        public string Matricule { get; set; }
        public string Genre { get; set; }
        public System.DateTime Jour { get; set; }
        public Nullable<decimal> NBJour { get; set; }
        public Nullable<decimal> NBHeure { get; set; }
        public System.DateTime JourFerie { get; set; }
    }
}
