//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassGetMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type5
    {
        public string Type_Jour { get; set; }
        public Nullable<decimal> T1_ { get; set; }
        public Nullable<decimal> T2_ { get; set; }
        public Nullable<decimal> T3_ { get; set; }
        public Nullable<decimal> T4_ { get; set; }
        public Nullable<int> T1Forfait { get; set; }
        public int T2Forfait { get; set; }
        public Nullable<int> T3Forfait { get; set; }
        public Nullable<int> T4Forfait { get; set; }
        public Nullable<int> Equivalent { get; set; }
        public Nullable<int> Carence { get; set; }
        public string Régle { get; set; }
    }
}
